name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    uses: percebus/github-actions-common/.github/workflows/dependency-review.yml@main
    permissions:
      contents: read
      pull-requests: read

  npm_audit:
    uses: percebus/github-actions-npm/.github/workflows/audit.yml@main

  pip-audit:
    name: pip-audit
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: percebus/github-actions-python/.github/actions/setup@main
      - uses: ./.github/actions/run_pip-audit
